In [1]:
import numpy as np

In [3]:
matrix = np.array([[1, 1, 1],
                   [1, 1, 10],
                   [1, 1, 15]])
np.linalg.matrix_rank(matrix)

2

In [4]:
matrix = np.array([[1, 2, 3], 
                   [2, 4, 6],
                   [3, 8, 9]])
np.linalg.det(matrix)


0.0

In [7]:
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])
matrix.diagonal()

array([1, 4, 9])

In [9]:
# Get a diagonal off from the main diagonal by using the offset parameter

In [10]:
matrix.diagonal(offset=1)

array([2, 6])

In [11]:
matrix.diagonal(offset=-1)

array([2, 8])

In [15]:
matrix = np.array([[1, -1, 3],
                   [1, 1, 6],
                   [3, 8, 9]])

eigenvalues, eigenvectors = np.linalg.eig(matrix)

print(eigenvalues)
print('\n')
print(eigenvectors)

[13.55075847  0.74003145 -3.29078992]


[[-0.17622017 -0.96677403 -0.53373322]
 [-0.435951    0.2053623  -0.64324848]
 [-0.88254925  0.15223105  0.54896288]]


In [16]:
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

np.dot(vector_a, vector_b)

32

In [ ]:
# Alternatively we can use the new @ operator

In [17]:
vector_a @ vector_b

32

In [18]:
matrix = np.array([[1, 4],
                  [2, 5]])
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [19]:
matrix @ np.linalg.inv(matrix)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [ ]:
# Generating random values

In [20]:
np.random.seed(0)
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])