In [2]:
import numpy as np
import torch
from torch import nn
from torchvision import datasets, transforms

In [3]:
torch.ones((2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [4]:
torch.ones((2,3), dtype=torch.int8)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int8)

In [5]:
torch.zeros((2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.zeros((2,3), dtype=torch.int8)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int8)

In [7]:
torch.full((3,3), 3.141592) 
# Note that the values are rounded off

tensor([[3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416]])

In [8]:
torch.empty((3,3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [9]:
torch.rand((2,3))

# Creates a tensor from a uniform distribution

tensor([[0.5097, 0.6703, 0.8973],
        [0.6701, 0.0364, 0.9166]])

In [11]:
torch.randn((3,3))

# Creates a tensor from a standard normal distribution

tensor([[-1.9162,  1.1811,  0.4281],
        [ 0.4750,  1.9064, -0.7326],
        [ 0.5569,  1.3560, -0.1682]])

In [12]:
torch.randint(10, 100, (2,3))

# Creates a tensor from a given range of values

tensor([[48, 64, 99],
        [64, 43, 96]])

In [13]:
# Creating a tensor from existing data
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
# Creating a reference tensor
a = torch.tensor([[1, 2, 3], [4, 5, 6]])

In [16]:
print(a.dtype)
print(a.shape)
b = torch.ones_like(a)
print(b)
print(b.dtype)
print(b.shape)

torch.int64
torch.Size([2, 3])
tensor([[1, 1, 1],
        [1, 1, 1]])
torch.int64
torch.Size([2, 3])


In [17]:
a.new_full((2, 2), 3.)

tensor([[3, 3],
        [3, 3]])

In [38]:
import numpy as np

a = np.ones((2, 3))
# Convert numpy array into a PyTorch tensor
b = torch.from_numpy(a)
print(b)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [25]:
# Convert a tensor to a numpy array
b = b.numpy()

In [29]:
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [39]:
# Changes in numpy are reflected in the tensor as well

print(a)
b = torch.from_numpy(a)
print('\n', b)

[[1. 1. 1.]
 [1. 1. 1.]]

 tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [40]:
a*=2
print(a)
print('\n', b)

[[2. 2. 2.]
 [2. 2. 2.]]

 tensor([[2., 2., 2.],
        [2., 2., 2.]], dtype=torch.float64)


In [44]:
x = torch.full((2,3), 4, requires_grad=True, dtype=torch.float64)
print(x)

tensor([[4., 4., 4.],
        [4., 4., 4.]], dtype=torch.float64, requires_grad=True)


In [45]:
y = 2*x+3
print(y)

tensor([[11., 11., 11.],
        [11., 11., 11.]], dtype=torch.float64, grad_fn=<AddBackward0>)


In [46]:
print(x)

tensor([[4., 4., 4.],
        [4., 4., 4.]], dtype=torch.float64, requires_grad=True)


In [47]:
y = (2*x**2+3)
print(y)

tensor([[35., 35., 35.],
        [35., 35., 35.]], dtype=torch.float64, grad_fn=<AddBackward0>)


In [48]:
# For this specific example y' = 4*x
# 4*4 = 16
y.backward(torch.ones_like(x))

In [51]:
print(x.grad)

tensor([[16., 16., 16.],
        [16., 16., 16.]], dtype=torch.float64)


In [52]:
x.requires_grad

True

In [53]:
x.requires_grad_(False) # Turning off gradient
x.requires_grad

False

In [55]:
# Changing the shape of a tensor

a = torch.Tensor([1, 2, 3, 4])
a = torch.reshape(a, (2,2))
print(a)

tensor([[1., 2.],
        [3., 4.]])


In [56]:
a = torch.Tensor([1, 2, 3, 4, 5, 6])
print(a.shape)

torch.Size([6])


In [57]:
a.resize_((2,2))

tensor([[1., 2.],
        [3., 4.]])

In [62]:
# The most common method to change the shape of a tensor

a = torch.Tensor([1, 2, 3, 4, 5, 6])
a = a.view((2,3))

In [63]:
print(a)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [64]:
# With the view() method you can shoose not to mention
# One of the dimensions arrange the rest of them, and
# PyTorch will calculate the mission dimension as follows

a.view((2, -1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [1]:
from fastai.text.all import *

ModuleNotFoundError: No module named 'fastai'