In [8]:
from numpy import diag, zeros, vstack
from numpy.random import rand, seed
from numpy.linalg import svd, pinv

seed(12345)
n = 5
p = 8
X = rand(n, p)
y = rand(n, 1)
U, S, VT = svd(X)

SI = diag(1/S)
pseudo_inv = VT.T @ vstack((SI, zeros((p-n,n)))) @ U.T
b = pseudo_inv @ y
print(X @ b - y)

[[2.22044605e-16]
 [7.77156117e-16]
 [1.11022302e-16]
 [4.44089210e-16]
 [5.55111512e-16]]


In [9]:
SI

array([[0.26824178, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.77795873, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 1.2811637 , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.52790728, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 3.07678138]])

In [13]:
vstack((SI, zeros((p-n, n))))

array([[0.26824178, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.77795873, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 1.2811637 , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.52790728, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 3.07678138],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])